### ISSUE TITLE
KeyError: 'Amino acid'

### ISSUE THREAD

**Issue by isahhin** [opensean/ptm#1]
Hi,    

pcp_aa_df = retrieve_pcp_compound(wiki_aa_df["Amino acid"])

For above code piece, an error occurs with following information: KeyError: 'Amino acid'. It can not find Amino Acid column.
I have printed the returned columns in wiki_aa_df. Then, the following columns are observed
Columns: [Biosynthetic pathways for catecholamines and trace amines in the human brain[74][75][76]  L-Phenylalanine L-Tyrosine L-DOPA Epinephrine Phenethylamine p-Tyramine Dopamine Norepinephrine N-Methylphenethylamine N-Methyltyramine p-Octopamine Synephrine 3-Methoxytyramine AADC AADC AADC primarypathway PNMT PNMT PNMT PNMT AAAH AAAH brainCYP2D6 minorpathway COMT DBH DBH Catecholamines and trace amines are synthesized from phenylalanine and tyrosine in humans.]

Could you help me. About this error. Thanks a lot.

**Comment by opensean** [comment]
Hi @isahhin,

It looks like the location of and the column titles of the table on Wikipedia have changed since I created this notebook.  If you edit  the ```retrieve_wiki_aa_table``` function in the "Helper Functions" section of the notebook to be as follows:

```
def retrieve_wiki_aa_table(page_name, table_int):
    """Retrieve a table from a wikipedia page.
    
    Args:
        page_name (str):  Name of the page, e.g. 'Amino acid'.
        table_int (int):  Number of table on the page, e.g. 2.
    
    Returns:
        pd.DataFrame: The table as a pandas dataframe.
    
    """
    cmap = {'Amino acid|Amino acid': "Amino acid",
            'Letter code|3': "3-letter",
            'Letter code|1': "1-letter",
            'Side chain|Class': "Side chain class",
            'Side chain|Polarity[130]': "Side chain polarity[136]",
            'Side chain|Charge, at pH\xa07.4[130]': "Side chain charge (pH 7.4)[136]",
            'Hydropathy index[127]|Hydropathy index[127]': "Hydropathy index[137]",
            'Molar absorptivity[128]|Wavelength, λmax (nm)': "Absorbance λmax(nm)[138]", 
            'Molar absorptivity[128]|Coefficient, ε (mM−1·cm−1)': "ε at λmax (mM−1 cm−1)[138]",
            'Molecular mass|Molecular mass': "MW (weight)",
            'Abundance in proteins (%)[129]|Abundance in proteins (%)[129]': "Occurence in proteins(%)[139]",
            'Standard genetic coding, IUPAC notation|Standard genetic coding, IUPAC notation': "Coding in the Standard Genetic Code"}
    
    p = wikipedia.page(page_name)
    all_tables = pd.read_html(p.html())
    wiki_aa = all_tables[table_int]
    wiki_aa.columns = ['%s%s' % (a, '|%s' % b if b else '') for a, b in wiki_aa.columns]
    return wiki_aa.rename(columns = cmap)

```

and change the following in the "4. Retrieve data from wikipedia and pubchem" section, the new wikipedia table will be retrieved and the columns will be mapped back to what the rest of the notebook is expecting.

change this 

```
## grab table from wikipedia
wiki_aa_df = retrieve_wiki_aa_table("Amino acid", 1)
```

to this 

```
## grab table from wikipedia
wiki_aa_df = retrieve_wiki_aa_table("Amino acid", 2)
```

I also just committed and pushed these changes to the master.

**Comment by isahhin** [comment]
Hi,
Thanks for your reply.
I also solved by reading an old version of given wikipedia page.

 url = requests.get("https://en.wikipedia.org/w/index.php?title=Amino_acid&oldid=839414740")
    p = url.text

    #p = wikipedia.page("w/index.php?title=Amino_acid&diff=959105521&oldid=958897998")
    all_tables = pd.read_html(p)
    wiki_aa = all_tables[1]
    loc1 = wiki_aa.loc[1:,:]
    loc0 = wiki_aa.head(0)

    loc00 = loc0.columns.values.tolist()
    loc000 = pd.Series(loc00)

    return loc1.rename(columns = loc000)
